% attack(Attacker, Deffender, Effectiveness)
attack( normal, normal,  1).
attack( normal, fire,  1).
attack( normal, water,  1).
attack( normal, electric,  1).
attack( normal, grass,  1).
attack( normal, ice,  1).
attack( normal, fighting,  1).
attack( normal, poison,  1).
attack( normal, ground,  1).
attack( normal, flying,  1).
attack( normal, psychic,  1).
attack( normal, bug,  1).
attack( normal, rock,  0.5).
attack( normal, ghost,  0).
attack( normal, dragon,  1).
attack( fire, normal,  1).
attack( fire, fire,  0.5).
attack( fire, water,  0.5).
attack( fire, electric,  1).
attack( fire, grass,  2).
attack( fire, ice,  2).
attack( fire, fighting,  1).
attack( fire, poison,  1).
attack( fire, ground,  1).
attack( fire, flying,  1).
attack( fire, psychic,  1).
attack( fire, bug,  2).
attack( fire, rock,  0.5).
attack( fire, ghost,  1).
attack( fire, dragon,  0.5).
attack( water, normal,  1).
attack( water, fire,  2).
attack( water, water,  0.5).
attack( water, electric,  1).
attack( water, grass,  0.5).
attack( water, ice,  1).
attack( water, fighting,  1).
attack( water, poison,  1).
attack( water, ground,  2).
attack( water, flying,  1).
attack( water, psychic,  1).
attack( water, bug,  1).
attack( water, rock,  2).
attack( water, ghost,  1).
attack( water, dragon,  0.5).
attack( electric, normal,  1).
attack( electric, fire,  1).
attack( electric, water,  2).
attack( electric, electric,  0.5).
attack( electric, grass,  0.5).
attack( electric, ice,  1).
attack( electric, fighting,  1).
attack( electric, poison,  1).
attack( electric, ground,  0).
attack( electric, flying,  2).
attack( electric, psychic,  1).
attack( electric, bug,  1).
attack( electric, rock,  1).
attack( electric, ghost,  1).
attack( electric, dragon,  0.5).
attack( grass, normal,  1).
attack( grass, fire,  0.5).
attack( grass, water,  2).
attack( grass, electric,  1).
attack( grass, grass,  0.5).
attack( grass, ice,  1).
attack( grass, fighting,  1).
attack( grass, poison,  0.5).
attack( grass, ground,  2).
attack( grass, flying,  0.5).
attack( grass, psychic,  1).
attack( grass, bug,  0.5).
attack( grass, rock,  2).
attack( grass, ghost,  1).
attack( grass, dragon,  0.5).
attack( ice, normal,  1).
attack( ice, fire,  1).
attack( ice, water,  0.5).
attack( ice, electric,  1).
attack( ice, grass,  2).
attack( ice, ice,  0.5).
attack( ice, fighting,  1).
attack( ice, poison,  1).
attack( ice, ground,  2).
attack( ice, flying,  2).
attack( ice, psychic,  1).
attack( ice, bug,  1).
attack( ice, rock,  1).
attack( ice, ghost,  1).
attack( ice, dragon,  2).
attack( fighting, normal,  2).
attack( fighting, fire,  1).
attack( fighting, water,  1).
attack( fighting, electric,  1).
attack( fighting, grass,  1).
attack( fighting, ice,  2).
attack( fighting, fighting,  1).
attack( fighting, poison,  0.5).
attack( fighting, ground,  1).
attack( fighting, flying,  0.5).
attack( fighting, psychic,  0.5).
attack( fighting, bug,  0.5).
attack( fighting, rock,  2).
attack( fighting, ghost,  0).
attack( fighting, dragon,  1).
attack( poison, normal,  1).
attack( poison, fire,  1).
attack( poison, water,  1).
attack( poison, electric,  1).
attack( poison, grass,  2).
attack( poison, ice,  1).
attack( poison, fighting,  1).
attack( poison, poison,  0.5).
attack( poison, ground,  0.5).
attack( poison, flying,  1).
attack( poison, psychic,  1).
attack( poison, bug,  2).
attack( poison, rock,  0.5).
attack( poison, ghost,  0.5).
attack( poison, dragon,  1).
attack( ground, normal,  1).
attack( ground, fire,  2).
attack( ground, water,  1).
attack( ground, electric,  2).
attack( ground, grass,  0.5).
attack( ground, ice,  1).
attack( ground, fighting,  1).
attack( ground, poison,  2).
attack( ground, ground,  1).
attack( ground, flying,  0).
attack( ground, psychic,  1).
attack( ground, bug,  0.5).
attack( ground, rock,  2).
attack( ground, ghost,  1).
attack( ground, dragon,  1).
attack( flying, normal,  1).
attack( flying, fire,  1).
attack( flying, water,  1).
attack( flying, electric,  0.5).
attack( flying, grass,  2).
attack( flying, ice,  1).
attack( flying, fighting,  2).
attack( flying, poison,  1).
attack( flying, ground,  1).
attack( flying, flying,  1).
attack( flying, psychic,  1).
attack( flying, bug,  2).
attack( flying, rock,  0.5).
attack( flying, ghost,  1).
attack( flying, dragon,  1).
attack( psychic, normal,  1).
attack( psychic, fire,  1).
attack( psychic, water,  1).
attack( psychic, electric,  1).
attack( psychic, grass,  1).
attack( psychic, ice,  1).
attack( psychic, fighting,  2).
attack( psychic, poison,  2).
attack( psychic, ground,  1).
attack( psychic, flying,  1).
attack( psychic, psychic,  0.5).
attack( psychic, bug,  1).
attack( psychic, rock,  1).
attack( psychic, ghost,  1).
attack( psychic, dragon,  1).
attack( bug, normal,  1).
attack( bug, fire,  0.5).
attack( bug, water,  1).
attack( bug, electric,  1).
attack( bug, grass,  2).
attack( bug, ice,  1).
attack( bug, fighting,  0.5).
attack( bug, poison,  2).
attack( bug, ground,  1).
attack( bug, flying,  0.5).
attack( bug, psychic,  2).
attack( bug, bug,  1).
attack( bug, rock,  1).
attack( bug, ghost,  0.5).
attack( bug, dragon,  1).
attack( rock, normal,  1).
attack( rock, fire,  2).
attack( rock, water,  1).
attack( rock, electric,  1).
attack( rock, grass,  1).
attack( rock, ice,  2).
attack( rock, fighting,  0.5).
attack( rock, poison,  1).
attack( rock, ground,  0.5).
attack( rock, flying,  2).
attack( rock, psychic,  1).
attack( rock, bug,  2).
attack( rock, rock,  1).
attack( rock, ghost,  1).
attack( rock, dragon,  1).
attack( ghost, normal,  0).
attack( ghost, fire,  1).
attack( ghost, water,  1).
attack( ghost, electric,  1).
attack( ghost, grass,  1).
attack( ghost, ice,  1).
attack( ghost, fighting,  1).
attack( ghost, poison,  1).
attack( ghost, ground,  1).
attack( ghost, flying,  1).
attack( ghost, psychic,  0).
attack( ghost, bug,  1).
attack( ghost, rock,  1).
attack( ghost, ghost,  2).
attack( ghost, dragon,  1).
attack( dragon, normal,  1).
attack( dragon, fire,  1).
attack( dragon, water,  1).
attack( dragon, electric,  1).
attack( dragon, grass,  1).
attack( dragon, ice,  1).
attack( dragon, fighting,  1).
attack( dragon, poison,  1).
attack( dragon, ground,  1).
attack( dragon, flying,  1).
attack( dragon, psychic,  1).
attack( dragon, bug,  1).
attack( dragon, rock,  1).
attack( dragon, ghost,  1).
attack( dragon, dragon,  2).